.github/workflows/lint-pr-title.yml

PR fixes the TODOs by repos being private
Reference: https://github.com/amannn/action-semantic-pull-request/issues/219
N/A
- [ X ] I've reviewed the guidance in CONTRIBUTING.md

ci: fix TODOs blocked by repos being private

---

.github/workflows/release.yaml

[53](https://github.com/runfinch/finch/issues/53)
Change to amd64 build to run on 10.15 macos to support finch on macos 10.15
N/A , can be tested on `main` branch since workflow is triggered by `workflow_dispatch` trigger. 

chore: Change amd64 runner to 10.15 OS version for build

---

.github/workflows/submodulesync.yaml

N/A
Commit by `submodulesync.yaml` workflow are not signed which leads to CI failing. [error](https://github.com/runfinch/finch-core/pull/14/checks?check_run_id=9806064207)
N/A, can only be run on the main branch. 

ci: Add signoff to sync submodule workflow

---

hashes/socket_vmnet-1.0.0-alpha.tar.gz.sha512

checksum check fails on macos 10.15 because of unsupported checksum format since macos 10.15 uses an older version of `shasum`. [error log](https://github.com/runfinch/finch/actions/runs/3587857287/jobs/6038648735)
Yes.

fix: Change checksum format to support macos 10.15 build

---

.github/workflows/release.yaml
Makefile
bin/download-sources.pl

N/A
GNU GPL [licence](https://www.gnu.org/licenses/gpl-3.0.en.html) requires us to distribute source code and license files along with the binary release. This process is currently managed manually. This change uploads the external sources using a github workflow. 
Changes:
1. Create tar ball which contains all the sources and licenses of finch dependencies and uploads to an s3 bucket for signing. 
Yes, locally. 

chore: Add script and workflow for downloading dependency sources

---

.github/workflows/submodulesync.yaml

N/A
1. Change trigger to cron expression for building deep dependencies. The build will run every Monday at 9am UTC. 
2. Sync lima dependency from latest release tag rather than `main` branch. 

ci: Change trigger to schedule and sync lima with release tags

---

.github/workflows/submodulesync.yaml

Fix to fetch remote tags for sub modules in order to checkout latest tag. 
Yes. 

fix: Add command to fetch remote tags

---

Makefile

Remove unnecessary dependency in `Makefile` for `download-sources` target. 
Yes

ci: Remove install-deps dependency in download-sources target

---

.github/workflows/release-please.yml
.github/workflows/upload-release-s3.yaml

Workflow to upload core release to s3. 
On a private repo with `robinraju/release-downloader@v1.7` action. 

ci: Add workflow to upload release artifacts to s3 on new release

---

.github/workflows/release-please.yml
.github/workflows/upload-release-s3.yaml

Change token to `GITHUB_TOKEN` since `FINCH_BOT_TOKEN` is read-only and cannot create releases. Change trigger of https://github.com/vsiravar/finch-core-public/blob/5300cecc342c5335ea501b56655c67f6b7295bd5/.github/workflows/upload-release-s3.yaml#L7 since resources created by `release-please` cannot trigger github actions as described [here](https://github.com/google-github-actions/release-please-action#github-credentials).  
Yes. 

ci: Revert back to GITHUB_TOKEN for release-please workflow

---

Makefile
hashes/socket_vmnet-1.0.0-alpha.tar.gz.sha512

Signed-off-by: Justin Alvarez <alvajus@amazon.com>
Issue #, if available: https://github.com/runfinch/finch/issues/21
Updates the socket_vmnet target to use the submodule which fixes the version issue.
- Tested locally with latest finch main commit:
```shell
$ make lima-socket-vmnet
$ ./_output/dependencies/lima-socket_vmnet/opt/finch/bin/socket_vmnet --version
> v1.1.0-4-g910aaef
```

fix: properly set socket_vmnet version

---

.github/workflows/submodulesync.yaml

Add `workflow_dispatch` trigger for off cycle submodule updates. 
Yes. Link: https://github.com/vsiravar/finch-core-public/actions/runs/4319003051

ci: Add workflow_dispatch trigger for off cycle release

---

.github/workflows/release.yaml

Fix typo which causes https://github.com/runfinch/finch-core/actions/runs/4352384603/jobs/7620373594 exception. 

ci: Fix typo in dependency build job

---

.github/workflows/release.yaml

Remove 10.15 runner support as 10.15 is deprecated officially

ci: Remove 10.15 support

---

.github/workflows/release.yaml

Disable auto builds until `limactl` dependency for macOS Ventura is managed in this repo. 
Yes. 

ci: Disable auto build until limactl ventrua dependency is managed

---

Makefile

Small quality-of-life improvement that checks whether the OS image has already been downloaded before trying to download again.
Before this change, my `finch` builds were taking in the range of 30 seconds - 3 minutes. After this change, most builds only take around 5 seconds.
```sh
make # image not downloaded, redownloads image
make # image downloaded, does not redownload
```

build: checks whether os image is already downloaded

---

.github/workflows/release.yaml
Makefile

https://github.com/runfinch/finch-core/issues/92
In order to support virtualization framework in finch, we need to build `limactl` binary for macOS 13. https://github.com/lima-vm/lima/blob/master/docs/vmtype.md#vz
* Build limactl dependency on macOS 12.6 with XCode 14.2.0 which has [macOS 13.1 SDK](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_2-release-notes). 
Yes. [Link](https://github.com/runfinch/finch-core/actions/runs/4747005052) 

ci: Add logic to build and package limactl binary for virtualization framework

---

.github/workflows/ci.yaml
.github/workflows/update-dependencies.yaml
Makefile
bin/update-deps.sh
e2e/e2e_test.go
e2e/fedora.yaml
e2e/go.mod

* Missing CI in finch-core. In the current state of finch-core, we don't have a way to ensure whether [dependencies built  and packaged by finch-core](https://github.com/runfinch/finch-core/blob/main/.github/workflows/release.yaml) work correctly, i.e they don't have any missing dependencies and the packaged set of dependencies can be used by `lima` based  systems such as finch. 
* We can also catch regressions in `limactl` and `nerdctl` before it is introduced to finch as the test will run against the `--subject=limactl nerdctl`. 
* Add e2e tests and workflow for merge validations. CI will run when a PR is opened against `main` branch. Tests can also be triggered by `workflow_dispatch`.  
* Workflow to update references to dependency package periodically in the …

ci: Add e2e tests for merge validations

---

.github/workflows/release.yaml
bin/lima-and-qemu.pl

The current build dependency workflow is broken since the auto scaling group removed the manual setting for xcode.
We switch to mac OS 13 to avoid manual setting in the future and fixed shell issue for brew and aws commands.
Made fixes in the build dependency action and switch to mac OS 13 to access xcode with expected version.
Have run the action on this branch: https://github.com/runfinch/finch-core/actions/runs/5082663399

ci: Fix build action

---

.github/workflows/rootfs.yaml
Dockerfile

https://github.com/runfinch/finch/issues/492
In order to facilitate Finch on Windows, we need a root filesystem. We will use this Dockerfile as a basis for that root filesystem - using `docker export` to turn a built container into an archived rootfs. For the scope of these changes, create the Dockerfile and an action that runs on changes to the file to build and push to ECR repo.
The Dockerfile will be used to create a container such that we can export that container's fs as a tarball and compress it for use with WSL2. For now, we are including cloud-init (at least for the WSL2 rootfs) but need further investigation to determine if we can remove the package to further slim the rootfs..
In order to create the container used as an …

feat: rootfs - build/upload action and Dockerfile

---

Makefile

$(MAKE) is used for calling `make` recursively. On a Windows machine, `make` might be at some location containing a space or special character, like /c/Program Files (x86)/GnuWin32/bin/make . Wrap in quotes as "$(MAKE)" to prevent errors.
`make` on macOS and Windows.

fix: quote recursive calls to make

---

bin/update-rootfs.sh

Ran script locally w/ `FINCH_ROOTFS_URL ?= https://deps.runfinch.com/common/aarch64/finch-rootfs-production-arm64-0000000000.tar.zst`, confirmed updated timestamp.

fix: use --recursive and correct pathing in update rootfs

---

bin/update-deps.sh
bin/update-rootfs.sh

The action "Sync Submodules and Dependencies" on finch failed with the message "set: Illegal option -o pipefail". 
https://github.com/runfinch/finch/actions/runs/5760444005/job/15616416221

ci: use bash instead of sh

---

Makefile

add rules to download rootfs for WSL support on Windows, group other rules (download Finch OS, vmnet_socket) by operating system
Building `finch` on a Windows EC2, I've set my submodules to be 
```
[submodule "deps/finch-core"]
path = deps/finch-core
url = https://github.com/ginglis13/finch-core.git
branch = windev
```
and successfully made `finch` / `finch-core`.
I also `make` and `make clean` `finch-core` on macOS

feat(make): support Windows

---

.github/workflows/rootfs.yaml

Change compression of rootfs bundle to gzip since windows does not come with zstd installed. 
Yes, locally. 

fix: Change rootfs compression to gzip

---

.github/workflows/release.yaml

N/A
Have checkout before setup-go to resolve cache warnings.

fix: setup-go in CI to resolve cache warnings

---

.github/workflows/ci.yaml
Dockerfile

install packages
* qemu-user-static-aarch64
* qemu-user-static-arm
* qemu-user-static-x86
* iptables
* fuse-sshfs 
depended on by lima to decrease boot time of Finch VM on Windows
* EC2 Windows dev instance 
* build rootfs locally, scp up
* run Finch w/ changes in runfinch/finch#553
* basic commands tests -> `finch vm init`, `finch vm pull alpine:latest`, etc.

perf: add lima dependency pkgs to speed up VM boot

---

.github/workflows/submodulesync.yaml

Track a known good commit main branch of lima submodule vs latest tag.
Yes

ci: track main branch of lima submodule

---

.github/workflows/submodulesync.yaml

Add ` fetch-depth: 0` to fetch all history for all branches and tags inorder to checkout stable commit. 

ci: add depth for fetching all branches and history

---

.gitmodules

Tracks a Lima fork until the SSH quoting issue is resolved upstream.
You probably need to run `git submodule set-url src/lima https://github.com/pendo324/lima` and `git submodule update --init --recursive` to get the latest changes

fix: track pendo324/lima windows-ssh-quoting until quoting fixed upstream

---

.gitmodules

- Since the ssh quote fix is merged, we can track Lima's `master` branch again

chore: track lima master now that quote fix is merged

---

.gitignore
Makefile
verify_hash.ps1

- Adds all dependencies needed to run lima/finch standalone
- This includes a lot of DLLs, need a better way to automate this
- TODO: after merge, need to modify Finch to set path when calling Lima so that these executables are actually used
- All exes work with an empty `%PATH%` (e.g. `$env:Path = ""; ssh.exe --help` works)

feat: add windows deps

---

Makefile

- Remove old version of msys-crypto
- Accidentally added because I looked at the DLLs required for an older version of `ssh-keygen.exe`, newer versions don't need this file
- Tested on my windows machine

fix: remove old version of msys-crypto

---

Makefile

tar option --force-local is used to instruct tar that the input is known to be a local file even if it is interpreted by tar to be a remote file; this appears to have been the case for the wingit local archive as seen in https://github.com/runfinch/finch/actions/runs/6501797014/job/17659749228
https://www.gnu.org/software/tar/manual/html_section/All-Options.html
`make` on windows instance

fix: use --force-local in tar

---

.github/workflows/cdk-e2e.yaml

Run cdk integration tests with finch as the drop in replacement for docker in cdk, i.e `CDK_DOCKER=finch`
Yes in fork, see https://github.com/vsiravar/finch-core-public/actions/runs/6126870804/job/16631723973

ci: add cdk e2e tests

---

.github/workflows/release.yaml

The dependency update step can exceed 1 hour, update the timeout to 2 hours
https://github.com/runfinch/finch-core/actions/runs/7098467075/job/19340092516

ci: Increase the dependency build timeout to 2 hours

---

.github/workflows/cdk-e2e.yaml

Install yarn on ec2 runners while executing cdk integration tests
Yes

ci: install yarn on runner  before yarn install

---

.github/workflows/submodulesync.yaml

Issue #, if available: e2e test failures on https://github.com/runfinch/finch/pull/649/
- Track Lima commit that fixes underlying issue with guestagent communication, which ultimately breaks port forwarding (which is why the e2e tests are failing). See https://github.com/lima-vm/lima/pull/2118 for more details
- tested on a Windows machine by compiling Lima

ci: track unreleased Lima commit to fix issue with Windows lima-guestagent communication

---

.github/workflows/cdk-e2e.yaml
.github/workflows/ci.yaml
.github/workflows/lint-pr-title.yml
.github/workflows/release-please.yml
.github/workflows/release.yaml
.github/workflows/rootfs.yaml
.github/workflows/submodulesync.yaml
.github/workflows/update-dependencies.yaml
.github/workflows/upload-release-s3.yaml

- actually checkout Lima version tags so that limactl --version correctly reports a tag instead of a commit hash
- https://github.com/runfinch/finch-core/compare/main...pendo324:finch-core:fix-lima-version?expand=1#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR27
- pinned all actions to commit hashes

fix: properly checkout lima tags and pin all actions

---

Dockerfile

- Update's cosign version to 2.2.3
- Also adds btrfs-progs, which is needed by cloud-init, but is missing in the last OS image
- Created a local image

chore: update cosign version 2.2.3

---

.github/workflows/release.yaml

- https://github.com/runfinch/finch-core/actions/runs/8988472547/job/24689380489#step:5:29
- Latest Lima release dropped support for golang 1.20, causing our builds to fail. This bumps the go version to 1.22.x

chore: update to go 1.22

---

.github/workflows/release-please.yml

- Follow [migration instructions](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration) from the old release-please since it is now archived. We don't really do releases for this repo, but we still have the code, so may as well migrate.

ci: migrate release-please action

---

.github/workflows/ci.yaml
Makefile
Makefile.darwin
Makefile.windows
e2e/e2e_test.go

Found while integrating ab5fc46 into finch.
This change updates install.lima-dependencies to unpack the lima archive into _output/lima on macOS and removes the lima template used for end-to-end testing as a macOS dependency.
`make` on finch using dirty submodule.

fix: lima dependencies on macOS

---

.github/workflows/ci.yaml
Makefile.windows
bin/verify_hash.ps1
deps/install.sh

Found during integration of 91c52d7 into finch.
```
deps/install.sh: line 75: shasum: command not found
+ grep -xq '^93ff4407f289f695424d3a4fe47158f712201d2b5ffcb0033a15d64e2082ddf8ef6e2f1612fa07ebb2bc9d57b38d0a5f3164fee1418d354847716e3594bd998d$'
+ echo 'error: shasum verification failed for dependency'
+ rm -f D:/a/finch-core/finch-core/_output/os/finch-rootfs-production-amd64-1715724303.tar.gz
error: shasum verification failed for dependency
+ exit 1
make: *** [Makefile.windows:27: D:/a/finch-core/finch-core/_output/os/finch-rootfs-production-amd64-171[57](https://github.com/austinvazquez/finch-core/actions/runs/9666641032/job/26666620967#step:4:58)24303.tar.gz] Error 1
```
This change fixes make install.dependencies on Windows. The …

fix: make install.dependencies on Windows

---

deps/install.sh

Found while integrating fd0402 in finch
This change fixes a typo in install.sh preventing MSYS Windows

fix: typo in install script preventing MSYS Windows

---

bin/update-deps.sh
bin/update-rootfs.sh
bin/utility.sh

In #326, it was found the update rootfs workflow was not working due to the filename pattern still searching for `.zst` archives. The pattern was updated to `.gz` to match the release archives in S3; however, the regular expression does not work with grep's basic regular expression engine.
This change updates the find in S3 utility function to use grep's extended regular expression engine and updates the filename patterns.
Tested using local aws S3 queries:
Rootfs bundle:
```
macedonv@localhost:~$ aws s3 ls s3://***/common/x86-64 --recursive | grep -E 'finch-rootfs-production-amd64-[0-9]+\.tar\.gz$' | tail -n 1 | sort | awk '{print $4}'
common/x86-64/finch-rootfs-production-amd64-1715724303.tar.gz
macedonv@localhost:~$ 
``` …

fix: update Finch on Windows rootfs update workflow

---

.github/workflows/rootfs.yaml

Found via https://github.com/runfinch/finch-core/actions/runs/9686368317
This change fixes the build rootfs workload to upload both the tarball and shasum to S3.

fix: build rootfs workflow for S3 upload

---

.github/workflows/rootfs.yaml

Found via https://github.com/runfinch/finch-core/actions/runs/9686876109
This change adds --recursive flag to the aws s3 cp command to apply the copy to S3 bucket to all files on the local path which match the artifact pattern.
Tested aws s3 cp locally using `--recursive` flag.

fix: build rootfs workflow not uploading the artifacts to S3

---

.github/workflows/ci.yaml
Makefile
Makefile.darwin
Makefile.windows
e2e/e2e_test.go

Closes #351 
This change updates the test matrix for e2e to test both Qemu and Virtualization framework (VZ) virtual machines on macOS.
CI is successful

ci: add virtualization framework (vz) testing

---

e2e/go.mod

Go in CI is using Go 1.22.0 even though new versions are available.
This change drops the patch version from the min version in go.mod.
CI is successful

ci: drop patch from Go min version

---

.github/workflows/release.yaml
.github/workflows/rootfs.yaml

`set-output` command is deprecated in GitHub Actions.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This change refactors generate timestamp steps in release and rootfs workflows to use the recommended method for setting outputs.

ci: remove set-output command usage

---

.github/workflows/release.yaml
.github/workflows/rootfs.yaml

Latest rootfs build did not have timestamp set.
This change fixes the set timestamp bug introduced with #342
Ran change in fork CI

ci: fix set timestamp output

---

Makefile.darwin
Makefile.windows
deps/install.sh

We can't cross-build if the arch is determined by `uname` at runtime. Instead, pass use `ARCH`.

build(fix): use arch that's passed in instead of system arch

---

.github/workflows/update-dependencies.yaml
bin/update-deps.sh
bin/update-os-image.sh
bin/update-rootfs.sh
bin/utility.sh

Base OS image updates have been manual by maintainers.
This change adds update base os image to the update dependencies workflow.
Locally tested regex to validate it produced the same result as the last update:
```
macedonv@localhost:/Volumes/workplace/finch-core$ aws s3 ls s3://*** --recursive | grep -E 'Fedora-Cloud-Base-.*\.aarch64-[0-9]+\.qcow2$$' | tail -n 1 | sort | awk '{print $4}'
Fedora-Cloud-Base-40-1.14.aarch64-20240626221713.qcow2
macedonv@localhost:/Volumes/workplace/finch-core$ 
```

ci: update base os image during update dependencies workflow

---

.gitignore

Update dependencies workflow is failing due to artifacts sizing. Artifacts are pulled in CI to validate SHASUMs are correct.
This change adds OS images to gitignore.
Ran update scripts locally and validated added entry to gitignore would exclude images.

ci: ignore OS image artifacts in update workflow

---

.github/workflows/release.yaml

Currently, we are using macOS 11 runners to build this archive. macOS 11 is deprecated, and we are no longer able to install our dependencies, which is causing runs to fail. 
<details>
<summary>Error excerpt for https://github.com/runfinch/finch-core/actions/runs/11342859343/job/31544196556#step:5:174
</summary>
```
==> Installing qemu dependency: python-packaging
==> Downloading https://ghcr.io/v2/homebrew/core/python-packaging/manifests/24.1_1
Already downloaded: /Users/ec2-user/Library/Caches/Homebrew/downloads/0a8b3181cb4fa8bee143a75cd85f08eb834903bde31ef0a291f3fe9f82bdbe41--python-packaging-24.1_1.bottle_manifest.json
==> Pouring python-packaging--24.1_1.all.bottle.tar.gz
🍺  /opt/homebrew/Cellar/python-packaging/24.1_1: 74 files, 545.5KB
==> Installing qemu
==> …
```

ci: update macOS runner version

---

.github/workflows/submodulesync.yaml
.gitmodules
Makefile

1. Adds a finch-core as a submodule, and adds building it to the `install.dependencies` target
2. Adds finch-core to the submodulesync workflow so that the latest tag is always used

build: add finch daemon

---

bin/lima-and-qemu.pl

Previous build failed due to incorrect directory path (source: https://github.com/runfinch/finch-core/actions/runs/11846730024/job/33014965223)
```
Config /Users/ec2-user/ar/_work/finch-core/finch-core/src/lima/examples/alpine.yaml not found at ./bin/lima-and-qemu.pl line 55.
```
This is because the examples directory is now the [templates directory](https://github.com/lima-vm/lima/tree/master/templates).
Added a way to detect when the new path to the templates should be used. This should be backwards compatible in case we have to roll our lima version back.
Local testing

fix: build script incorrect path

---

.github/workflows/submodulesync.yaml
.github/workflows/update-dependencies.yaml

#434 
This change updates the update workflows to use their own PR branch.

ci: use separate pull request branch per update workflow

---

lima-template/fedora.yaml

1/2 for #435
This change is a workaround for lima bundle updates blocked by nerdctl full archives.

chore(deps): pin nerdctl full archive to v1.7.7

---

.github/workflows/rootfs.yaml

Adding this workflow to update windows rootfs digest and artifact name in rootfs.conf
Created a branch and ran the workflow to see the pr is generated with the correct changes.
Reference PR Link: https://github.com/runfinch/finch-core/pull/445/files

feat: Add workflow to update windows hash and filename

---

.github/workflows/ci.yaml
.github/workflows/macos-ci.yaml
.github/workflows/windows-ci.yaml

This change refactors the GitHub Actions CI to split macOS and Windows verification such that macOS tests run only when its files change and vice-versa for Windows. The benefit is reduced contention for runners when pushing platform pull requests for Windows and macOS.

ci: refactor platform specific GHA CI

---

.github/dependabot.yaml

https://github.com/runfinch/finch-core/pull/478 introduced a mechanism for dependabot to open update PR's for cosign. The configuration is incorrect.
See https://github.com/runfinch/finch-core/runs/35000416717
Documentation: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#dependency-type-allow
This change updates the dependabot configuration for direct dependencies only. i.e. cosign itself.

ci: fix dependabot configuration

---

.github/workflows/macos-ci.yaml

#490 did not run macOS CI for the lima update.
This change fixes macOS CI to run on lima bundles update.

ci: run macos CI on lima bundle updates

---

.github/workflows/macos-ci.yaml

Regression introduced by #471
This change adds src/socket_vmnet git submodule to the allowlist for macOS CI.

ci: run ci on socket_vmnet submodule updates

---

.github/workflows/update-dependencies.yaml

This change fixes the update dependencies workflow for updating nerdctl archives.
Ran in fork.

fix: container runtime full archive upstream update

---

rootfs/Dockerfile

Fixes #553 
Exclude `audit` and `audit-rules` package during group install.
They are excluded by exact name, because there are packages in groupinstall which requires `audit-libs`.
I uninstalled these packages in Lima using dnf command and restarted system, so, systemd would startup w/o degradation.
Can't find this file in this repo.

fix: Skip audit and audit-rules installation in rootfs for Windows WSL2

---

rootfs/Dockerfile

Fedora 40 got deprecated, updating to fedora 41.

chore: update fedora OS to 41

---

.github/workflows/release.yaml
bin/lima-and-qemu.pl
e2e/go.mod
lima-template/fedora.yaml

- Upgrades the macOS version used to package Lima binaries (**this will stop Finch from working on macOS 12**)
- Explicitly use qemu virtualization so that we package the QEMU binaries
- Upgrades the go.mod version
- Fixes an issue with the QEMU e2e tests due to a kernel bug with Lima's default `mountType`

fix: qemu and build issues

---

.github/workflows/update-dependencies.yaml

This PR improves the security of the `update-dependencies.yaml` file. Following the best practices mentioned in the [github actions security hardening guidelines](https://docs.github.com/en/actions/reference/security/secure-use#use-an-intermediate-environment-variable)
- Use an intermediate variable for user inputs to prevent script injection

ci: use intermediate env variable for nerdctl tag override in workflow
