- .github/workflows/release-please.yml
Fix finch bot token to read from github secrets. 
> ci: Add finch bot token from github secrets

- .github/workflows/release.yaml
- Makefile
N/A
Currently we upload dependency sources for both architectures which is excessive. This change ensures that we only upload 1 version of sources.
Yes, locally. 
> ci: Refactor dependency download workflow and add clean up

- .github/workflows/submodulesync.yaml
- bumps submodules to latest versions
- this includes switching to lima's master branch for now to include a new feature before the next Lima release is cut
- local testing
> chore: bump submodules

- .github/workflows/submodulesync.yaml
Track lima release instead of main branch for lima submodule. 
> ci: Change submodule update to track tag for lima

- .github/workflows/release.yaml
Remove `shell: zsh {0}`  from ubuntu runners in [release](https://github.com/runfinch/finch-core/blob/main/.github/workflows/release.yaml) workflow. 
N/A. 
- [X ] I've reviewed the guidance in CONTRIBUTING.md
> ci: Remove shell settings on ubuntu runners for release

- .github/workflows/rootfs.yaml
use aws-actions/amazon-ecr-login@v1 to configure credentials / get authorization token to Amazon ECR.
act, local repo.
> fix: add ecr authentication

- .github/workflows/rootfs.yaml
fix issue in setting timestamp label
> fix: add timestep stamp to generating rootfs

- .github/workflows/submodulesync.yaml
Fix indentation level of the comment to match the current indentation level.
Yes, validated to be a valid yaml file. 
> ci: fix indentation in workflow

- Dockerfile
> feat: add cosign to rootfs

- .github/workflows/rootfs.yaml
- Makefile
- Update rootfs archive
- Remove arm64 build for rootfs
> build(deps): update rootfs

- Makefile
- Accidentally removed from previous PR
> chore: add ssh-keygen and deps

- .github/workflows/submodulesync.yaml
- track lima's release(tags) in submodules 
- bump lima version to 0.18.0
> chore: track lima release

- Dockerfile
Address a nit in the style of the Dockerfile, with the added bonus that this will trigger an update to the rootfs and in tern include patches for packages.
> chore: update rootfs and Dockerfile style nit

- Makefile
- Update Windows rootfs
- Tested on Windows machine
> chore: update Windows rootfs

- .github/workflows/submodulesync.yaml
- Switch back to latest Lima now that upstream commit got released
> ci: track latest lima tag

- .github/workflows/release.yaml
- #248 worked to fetch tags for the main repo, _but not submodules_. Added new step to fetch tags for all submodules.
- Also ran a formatter since I noticed some inconsistencies in the file
> fix: properly checkout submodule tags

- .github/workflows/cdk-e2e.yaml
Install go, lz4, automake, autoconf, libtool necessary to build finch. 
Yes
> ci(deps): install dependencies for finch build

- Makefile
- updates Windows rootfs image
> chore: update Windows rootfs to Fedora 39

- Dockerfile
- Updates Dockerfile to Fedora 40
- Adds verification for cosign's rpm file before installing it in the final rootfs
- Local testing
> chore: update dockerfile for fedora 40

- deps/full-os.conf
This PR updates the hashes and IDs for darwin aarch64 artifacts.
> build(deps): Update darwin aarch64 hashes and IDs

- .github/dependabot.yaml
Fixes https://github.com/runfinch/finch-core/runs/35000554369
> ci: fix dependabot configuration array

- Makefile
> fix: clean make target
